package ticketingsystem;

import java.util.LinkedHashSet;
import dataobjects.*;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import static utils.CFormat.*;
import utils.SelectOption;
import static utils.SelectOption.*;

/**
 * Ticketing System is the main class for the TicketingSystem application
 * @author CQD2 Software
 * Contributors:
 *      David Emery
 *      Quinn Detweiler
 *      David Grant
 *      Corbin Hall
 */
@SuppressWarnings("CallToThreadDumpStack")
public class TicketingSystem implements Runnable {

    //=====================  Constants  ==========================//
    public static final int ADMIN = 1;    //level of an admin user
    public static final int STANDARD = 0; //level of a standard user
    //=====================  Instance Variables  ======================//
    private Technician currentUser = null;  //authenticated user, null if not authenticated
    private Tickets tickets = new Tickets();  //tickets database table access
    private Entries entries = new Entries();
    private TicketEntries ticketEntries = new TicketEntries();
    private Technicians technicians = new Technicians();
    private TicketTechnicians ticketTechnicians = new TicketTechnicians();    //ticketTechnicians database table access
    private Scanner keyboard = new Scanner(System.in);

    /**
     * Main method for the TicketingSystem application which starts a new
     * thread and runs the application
     * @param args
     * @throws Exception 
     */
    public static void main(String[] args) throws Exception {

        //kick off a new TicketingSystem thread
        Thread t = new Thread(new TicketingSystem());
        t.start();
    }

    /**
     * run() begins program execution
     */
    @Override
    public void run() {

        System.out.println(titleBox("CQD2 Ticketing System"));
        boolean validated = false;
        int counter = 0;
        do {
            System.out.println("Enter username: ");
            String username = keyboard.nextLine();
            System.out.println("Enter password: ");
            String password = keyboard.nextLine();

            login currLogin = new login(username, password);
            
            try{
                if (currLogin.validate()) {
                    validated = true;
                    try {
                        currentUser = technicians.fetchByUsername(username);
                    } catch (Exception ex) {
                        System.out.println("Error fetching current user!");
                    }

                    //reset counter
                    counter = 0;

                } else {
                    counter++;
                    validated = false;
                    System.out.println("Invalid username/password!");
                }
            }catch(Exception e){
                //if there is an error generated by Login.validate()
                //there was a problem fetching info from database
                //print message and exit
                System.out.println("Unable to authenticate at this time.");
                System.exit(0);
            }
        } while (!validated && (counter < 3));
        

        //if counter is 3, there were too many login attempts
        if (counter == 3) {
            System.out.println("Too many invalid authentication attempts. Program will now exit");
            System.exit(0);

            //if counter is not 3, login was successful and we should proceed
            //to the main menu
        } else {
            mainMenu();
        }

    } // End of main

    /**
     * Display the main menu for the TicketingSystem.  Output will
     * depend on whether the authenticated user is a standard user or an
     * administrator
     * @pre currentUser is not null (there is an authenticated user)
     */
    public void mainMenu() {

        //=====================  Local Data  ======================//
        char response;  //used to store user option selection
        boolean quit = false;   //whether main menu should be quit or not
        String prompt = "Please select one of the following options.";


        //menu wrapped in do-while so there is an opportunity to confirm
        //quitting the application
        do {

            //if user is a standard user, display the standard menu
            if (currentUser.getLevel() == ADMIN) {

                String[] standardOpts = //standard menu options
                        {
                    "1 - View tickets",
                    "2 - Add a ticket",
                    "3 - Add a technician",
                    "4 - Assign a technician",
                    "q - Quit"
                };
                response = variableOption(prompt, standardOpts, '1');

                switch (response) {

                    //view all tickets
                    case '1':
                        viewTicketsMenu();
                        break;

                    //add a ticket
                    case '2':
                        try {
                            addTicket();
                        } catch (Exception ex) {
                            ex.printStackTrace();
                        }
                        break;

                    //add a technician
                    case '3':
                        addTechnician();
                        break;

                    //modify technician level
                    case '4':
                        assignTechnician();
                        break;

                    //quit program
                    case 'Q':

                        //if quit is confirmed, set quit to true so menu loop
                        //will end
                        if (yesNoOption("Are you sure you want to quit?", true)) {
                            quit = true;
                        }
                        break;
                }//end switch


            }//end if standard user
            else {
                String[] standardOpts = //standard menu options
                        {
                    "1 - View tickets",
                    "2 - Add a ticket",
                    "q - Quit"
                };
                response = variableOption(prompt, standardOpts, '1');

                switch (response) {
                    //view assigned ticket
                    case '1':
                        viewTicketsMenu();
                        break;

                    //add a ticket
                    case '2':
                        try {
                            addTicket();
                        } catch (Exception ex) {
                            ex.printStackTrace();
                        }
                        break;

                    case 'Q':

                        //if quit is confirmed, set quit to true so menu loop
                        //will end
                        if (yesNoOption("Are you sure you want to quit?", true)) {
                            quit = true;
                        }
                        break;
                }
            }

        } while (!quit);

    }

    /**
     * viewTicketsMenu displays the menu for viewing and selecting tickets
     * for the current user
     * @pre currentUser is not null (there is an authenticated user)
     */
    public void viewTicketsMenu() {

        //=====================  Local Data  ======================//
        boolean quit = false;

        //wrap in do while to allow repetition of menu
        do {

            //if logged in user is a standard user, get a list of all tickets
            //assigned to him/her
            Collection<Ticket> ticketSet = null;
            try {
                if (currentUser.getLevel() == STANDARD) {
                    ticketSet = tickets.fetchAllForTechnician(currentUser.getID());
                } else {
                    ticketSet = tickets.fetchAll();
                }
            } catch (Exception e) {

                //if there is an error fetching from the database
                //print an error message to the console and then return
                //to previous procedure (previous menu)
                System.out.println("Error connecting to database.  Please try again");
                return;
            }

            //print header
            if(currentUser.getLevel() == STANDARD){
                System.out.println(head("Assigned Tickets"));
            } else {
                System.out.println(head("All Tickets"));
            }
            //if there are tickets for the user, print tickets formatted by id

            Collection<Integer> ticketIDs = new HashSet<>();
            if (!ticketSet.isEmpty()) {
                for (Ticket t : ticketSet) {

                    //store ticket IDs for selection later
                    ticketIDs.add(t.getID());
                    System.out.print(item(t.getID() + ": " + t.getTitle(), 1));

                }
                System.out.println(""); //for formatting purposes

                //allow user to select a ticket or quit
                String[] options = {
                    "Ticket ID number to view details",
                    "l - list tickets again",
                    "q - return to the main menu"
                };
                String prompt = "Please enter one of the following:";

                String response = complexVariableOption(prompt, options, 1, ticketIDs, 'l');

                //user entered a valid ticket ID
                if (response.charAt(0) == 'I') {

                    //go to the submenu for this ticket
                    int ticketID = Integer.parseInt(response.substring(1));
                    System.out.println("Ticket " + ticketID + " selected.");
                    ticketSubMenu(ticketID);

                    //user asked to list tickets
                } else if (response.charAt(1) == 'L') {
                    //do nothing to loop the menu again
                } else if (response.charAt(1) == 'Q') {
                    //System.out.println("Quit");
                    quit = true;
                }

                //if there are not tickets for the user, print out message
            } else {
                System.out.println("You have no assigned tickets!");
            }

        } while (!quit);
    }

    /**
     * ticketSubMenu allows a user to manipulate information about a
     * particular ticket
     * @param ticketID t
     */
    public void ticketSubMenu(int ticketID) {

        while (true) {
            String[] standardOptions = {
                "1 - View ticket details",
                "2 - Add entry", // DavidE
                "q - Go Back"
            };
            String[] adminOptions = {
                "1 - View ticket details",
                "2 - Add entry", // DavidE
                "3 - Assign Technician",
                "q - Go Back"
            };
            
            String prompt = "Please select one of the following options";

            char choice = 'l'; //hold user's menu choice

            if (currentUser.getLevel() == STANDARD) {
                choice = SelectOption.variableOption(prompt, standardOptions, '1');
            } else if(currentUser.getLevel() == ADMIN) {
                choice = SelectOption.variableOption(prompt, adminOptions, 'l');  
            }
            
            switch (choice) {

                case '1':
                    viewTicket(ticketID);
                    break;
                case '2':
                    try {
                        addEntry(ticketID);
                        viewTicket(ticketID);
                    } catch (Exception ex) {
                        System.out.println("Unable to add entry");
                        ex.printStackTrace();
                    }
                    break;
                    
                //case three is only accessible to admins based on the
                //options sent to SelectOption.variableOption()
                case '3':
                    assignTechnician();
                    break;
                case 'Q':
                    //leave method to return to previous menu
                    return;
            }
        }
    }

    //displays ticket details based on user entry
    public void viewTicket(int ticketID) {

        //=====================  Local Data  ======================//
        Ticket ticket;  //ticket to view details from

        try {
            ticket = tickets.fetch(ticketID);
        } catch (Exception e) {
            System.out.println("Unable to display info for this ticket.");
            return;
        }

        //build table based on ticket info
        ArrayList<ArrayList<String>> table = new ArrayList<>();

        //general info
        ArrayList<String> row1 = new ArrayList<>();
        row1.add("Ticket ID:");
        row1.add(Integer.toString(ticket.getID()));
        table.add(row1);
        ArrayList<String> row2 = new ArrayList<>();
        row2.add("Date Created:");
        row2.add(ticket.getDateCreatedString().toString());
        table.add(row2);
        ArrayList<String> row3 = new ArrayList<>();


        //assigned technicians
        List<Technician> techs = null;
        try {
            techs = ticketTechnicians.fetchTechniciansByTicketID(ticketID);
        } catch (Exception e) {
            //TODO improve error handling here in future release
            System.out.println("Unable to display info for this ticket.");
            return;
        }

        //if there are techs to add, add them to the list
        if (techs != null && !techs.isEmpty()) {
            //make first row of tech info have row title
            ArrayList<String> row4 = new ArrayList<>();
            row4.add("Assigned Technicians:");
            row4.add(techs.get(0).getUsername());
            table.add(row4);

            for (int i = 1; i < techs.size(); i++) {
                row4 = new ArrayList<>();
                row4.add("");
                row4.add(techs.get(i).getUsername());
                table.add(row4);
            }
        }

        //print out title
        System.out.println(head("Ticket Info:"));

        //print out description
        System.out.println(ticket.getTitle());

        //print table out
        System.out.println(toTable(table, false));

        //print out ticket entries - David E: ================================//
        Entry entry;

        // entries for ticket:
        List<Entry> entriesList = null;
        try {
            entriesList = entries.fetchAllFromTicket(ticketID);
        } catch (Exception e) {
            //TODO improve error handling here in future release
            System.out.println("Unable to display entries for this ticket.");
            return;
        }

        if (entriesList.isEmpty()) {
            System.out.println("This Ticket has no entries.");
        } else {
            System.out.println("Entries: ");
        }

        // One table for every entry: 
        for (int i = 0; i < entriesList.size(); i++) {
            entry = entriesList.get(i);
            //build a table based on entries
            ArrayList<ArrayList<String>> entryTable = new ArrayList<>();
            ArrayList<String> entryRow1 = new ArrayList<>();
            entryRow1.add("Entry ID:");
            entryRow1.add(Integer.toString(entry.getID()));
            entryTable.add(entryRow1);
            ArrayList<String> entryRow2 = new ArrayList<>();
            entryRow2.add("Creation Date:");
            entryRow2.add(entry.getCreationDate());
            entryTable.add(entryRow2);
            ArrayList<String> entryRow3 = new ArrayList<>();
            entryRow3.add("Creator:");
            entryRow3.add(entry.getCreator());
            entryTable.add(entryRow3);
            ArrayList<String> entryRow4 = new ArrayList<>();
            entryRow4.add("Text:");
            entryRow4.add(entry.getText());
            entryTable.add(entryRow4);

            //print the entryTable out
            System.out.print(toTable(entryTable, false));
        }

    } // End of viewTicket.

    //creates a ticket entry which is by default assigned to the creator. Only technicians with
    //level 1 or > 0 can assign this ticket to a different technician
    // UI-G/14: DavidE
    public void addTicket() throws Exception{

        String title;
        String status;
        String creator;
        String client;
        String dateCreated;
        
        System.out.println("title: ");
        title = keyboard.nextLine();
        System.out.println("status: ");
        status = keyboard.nextLine();
        
        creator = currentUser.getName();
//        System.out.println("creator: ");
//        creator = keyboard.nextLine();
        System.out.println("client: ");
        client = keyboard.nextLine();
 
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        dateCreated = dateFormat.format(date);
//        System.out.println("dateCreated: ");
//        dateCreated = keyboard.nextLine();
        
        Ticket t = tickets.add(title, status, creator, client, dateCreated);
        
        assignTechnician(currentUser.getID(), t.getID());
        
        //add first entry
        addEntry(t.getID());
    }

    // Creates an entry and links it to the ticket specified by the parameter(ticketID):
    public void addEntry(int ticketID) throws Exception {
        Entry entry;
        String creationDate;
        String creatorName;
        String text;

        //set creationDate and creatorName based on system information
        //to limit amount of input needed from user
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        creationDate = dateFormat.format(date);
        creatorName = currentUser.getName();
        
//        System.out.println("creationDate:");
//        creationDate = keyboard.nextLine();
//        System.out.println("creatorName:");
//        creatorName = keyboard.nextLine();
        System.out.println("text:");
        text = keyboard.nextLine();

        // creates entry in DataBase:
        entry = entries.add(creationDate, creatorName, text);

        // links entry to ticket:
        ticketEntries.add(entry.getID(), ticketID);
    }

    //update ticket information with limitations based on technician level
    public void updateTicket() {
    }

    //deletes or closes the ticket in question. only technicians with level > 0 can do this.
    public void deleteTicket() {
        String line = prompt("Ticket ID to remove (-1 to cancel): ");
        try {
            int id = Integer.parseInt(line);
            if (id != -1) {
                try {
                    tickets.remove(id);
                } catch (Exception e) {
                    System.err.println("Unable to delete ticket " + id);
                }
            } else {
                System.out.println("Cancelled remove.");
            }
        } catch (NumberFormatException e) {
            System.out.println("Error: Not a number.");
        }
    }
    
    public void assignTechnician(){

        Collection<Technician> allTechs;
        Collection<Ticket> allTickets;
        int technician_id;
        int ticket_id;
        
        
        //grab lists of technicians and tickets
        try{
            allTechs = technicians.fetchAll();
            allTickets = tickets.fetchAll();
        }catch(Exception e){
            System.out.println("Unable to assign ticket at this time.");
            return;
        }
        
        //if there are no tickets, assignment is impossible
        if(allTickets.isEmpty()){
            System.out.println("No tickets available for assignment");
            return;
        }
        
        //create map associating tech names with their
        //id's for selection
        Map<String, Integer> techMap = new HashMap<>();
        for(Technician t : allTechs){
            techMap.put(t.getUsername(), t.getID());
        }
        
        //create map associating ticket titles with their
        //id's for selection
        Map<String, Integer> ticketMap = new HashMap<>();
        for(Ticket t : allTickets){
            ticketMap.put(t.getTitle(), t.getID());
        }
        
        String prompt = "Select a technician from the following:";
        technician_id = SelectOption.autoIntegerOption(prompt, techMap);
        
        prompt = "Select a ticket from the following:";
        ticket_id = SelectOption.autoIntegerOption(prompt, ticketMap);
    
        
        System.out.println("techID=" + technician_id + ";  ticketID=" + ticket_id);
        assignTechnician(technician_id, ticket_id);
        System.out.println("Assignment complete.");
        
    }

    //adds a new entry into the technician table. only technicians with level > 0 can do this.
    public void addTechnician() {
        
        //=====================  Local Data  ======================//
        String username, password, name;
        int level;
        
        boolean entryFinished = false;
        
        do{

            //get technician information
            System.out.println("Enter the following information about the technician");
            System.out.println("Username");
            username = keyboard.nextLine();
            System.out.println("Password");
            password = keyboard.nextLine();
            System.out.println("Name");
            name = keyboard.nextLine();
            char levelChar = SelectOption.variableOption("Select a level:", 
                    new String[]{"a = Admin", "s = Standard"}, 's');
            level = (levelChar =='A') ? 1 :  0; 

            //add technician
            try{
                Technician t = technicians.add(username, password, name, level);
                entryFinished = true;
            } catch(SQLException sqle){

                if(sqle.getSQLState().equals("23000")){
                    System.out.println("Duplicate name not allowed.");
                } else {
                    System.out.println("Unable to add technician at this time." 
                        + NL + "Please try again later.");
                }

            } catch(Exception e){

                System.out.println("Unable to add technician at this time." 
                        + NL + "Please try again later.");
            }
            
        } while (!entryFinished);
        
    }

    //modifies the level of the technician. only technicians with level > 0 can do this.
    public void modifyTechnicianLevel() {
    }

    // View the information for a single technician
    public void viewTechnician() throws Exception {
        String username = prompt("Technician User Name: ");
        System.out.print(technicians.fetchByUsername(username).toString());
    }

    public void viewAllTechnicians() throws Exception {
        Collection<Technician> techs = technicians.fetchAll();

        Iterator<Technician> itr = techs.iterator();
        while (itr.hasNext()) {
            Technician tech = itr.next();
            System.out.println(tech.toString());
        }
    }

    private String prompt(String message) {
        System.out.print(message);
        Scanner sc = new Scanner(System.in);
        return sc.nextLine();
    }

    private void assignTechnician(int technician_id, int ticket_id) {
        try{
            ticketTechnicians.add(technician_id, ticket_id);
        }catch(Exception e){
            System.out.println("Unable to assign technician at this time");
        }
    }
}
